name: "Arnaout Lab @ UCSF"
description: "This is the official web page for the Rima Arnaout Lab at UCSF -- UNDER CONSTRUCTION"

url: "http://arnaoutlab.ai"

paginate: 5
gems: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown: 
  parse_block_html: true
